tests: dkms: a more comprehensive test
* Try loading (almost) all modules
* And cleanup afterwards
* The linux-headers are only reommended by dkms.
* That said, the test fails to build due to install order issues.
  - So skip if it fails to install.
  - Hopefully I can find a fix for that later.

Signed-off-by: Tzafrir Cohen <tzafrir@debian.org>

diff --git a/debian/tests/dkms-modules b/debian/tests/dkms-modules
--- a/debian/tests/dkms-modules
+++ b/debian/tests/dkms-modules
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+#excluded_modules="dahdi_dummy|dahdi_vpmadt032_loader"
+# * dahdi_vpmadt032_loader: architecture-dependent. May not exist
+# * dahdi_echocan_oslec: fails for an odd reason. No time to figure this
+#   now. Loads and works fine in the m-a test.
+excluded_modules="dahdi_vpmadt032_loader|dahdi_echocan_oslec"
+dkms_conf="debian/dkms.conf.in"
+skip_status=77
+
 #
 # Check DKMS installation
 #
@@ -7,7 +15,7 @@ dkms status
 dkms status -k $(uname -r) | grep -q ": installed"
 if [ $? -ne 0 ]; then
 	echo "DKMS installation: failed for $(uname -r)!"
-	exit 1
+	exit $skip_status
 fi
 echo "DKMS installation: OK"
 
@@ -17,19 +25,28 @@ echo "DKMS installation: OK"
 
 set -e
 
-# dahdi_vpmadt032_loader is architecture-dependent
-modules=`awk -F'"' '/^BUILT_MODULE_NAME/ {print $2}' debian/dkms.conf | grep -v dahdi_vpmadt032_loader`
+# Excuded modules:
+# * dahdi_vpmadt032_loader is architecture-dependent
+# * dahdi_dummy: should not be on this list. It is not built
+modules=`awk -F'"' '/^BUILT_MODULE_NAME/ {print $2}' $dkms_conf | grep -E -v "$excluded_modules"`
 
 echo "Unloading any existing modules:"
 /usr/share/dahdi/dahdi-modules unload
 echo "Loading all modules: $modules"
+find /lib/modules/$(uname -r) -name '*.ko' | grep dahdi
 for module in $modules; do
-	modprobe $module
+	if ! modprobe $module; then
+		dmesg | tail
+		echo "Failed to load module $module."
+		exit 1
+	fi
 done
 
 echo "Unloading them all again"
 /usr/share/dahdi/dahdi-modules unload
-modprobe -r echo
+if lsmod | grep -w echo; then
+	rmmod echo
+fi
 
 # uninstall, to not get in the way of the m-a test
 dkms uninstall dahdi/`dkms status dahdi | cut -d, -f2 | head -n1` --all
